name: .NET

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        directory: '/home/runner/work/DBC2CSV/DBC2CSV/DBC2CSV/bin/Release/net6.0'
        type: 'zip'
        filename: 'Release.zip'
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Release.zip
        asset_name: Release
        tag: ${{ github.ref }}
        overwrite: true
        body: "Latest release"
